/**
 * 제품 데이터
 * - categories: 대분류 목록 (id, 이름, 설명, 아이콘)
 * - products: 개별 제품 목록 (category 로 대분류와 연결)
 * 화면(HTML)과 데이터를 분리해 두어, 제품 추가/수정은 이 파일만 고치면 됩니다.
 */

const CATEGORIES = [
  {
    id: "chromatography",
    name: "크로마토그래프 · 질량분석기",
    short: "Chromatography & MS",
    desc: "HPLC, LC/MS, GC, GC/MS 등 분리·정성·정량 분석의 핵심 장비",
    icon: "🧪",
  },
  {
    id: "spectroscopy",
    name: "광분석장치",
    short: "Spectroscopy",
    desc: "UV, FTIR, 형광, 원자흡광, ICP 등 빛을 이용한 성분 분석 장비",
    icon: "🌈",
  },
  {
    id: "lifescience",
    name: "라이프사이언스 연구장비",
    short: "Life Science",
    desc: "핵산·단백질 분석, 전기영동, MALDI-TOF, 뇌기능 이미징 장비",
    icon: "🧬",
  },
  {
    id: "environmental",
    name: "환경측정장치",
    short: "Environmental",
    desc: "총유기탄소(TOC), 온라인 모니터링, 휴대용 가스 분석 장비",
    icon: "🌱",
  },
  {
    id: "material",
    name: "재료시험기 · 피로/내구시험",
    short: "Material Testing",
    desc: "만능 재료 시험기, 피로·내구, 경도, 점도 등 물성 평가 장비",
    icon: "⚙️",
  },
  {
    id: "particle",
    name: "입도분석기 · 전자저울",
    short: "Particle & Balance",
    desc: "입도 분포 측정, 정밀 전자저울, 수분 측정 등 계량 장비",
    icon: "⚖️",
  },
  {
    id: "xray",
    name: "X선 형광분석기",
    short: "X-ray Fluorescence",
    desc: "에너지 분산형 형광 X선(EDX) 등 비파괴 원소 분석 장비",
    icon: "☢️",
  },
  {
    id: "ndt",
    name: "비파괴분석기 · 주사탐침현미경",
    short: "NDT & SPM",
    desc: "X선 CT 비파괴 검사, 초음파 탐상, 주사탐침현미경(SPM)",
    icon: "🔬",
  },
  {
    id: "consumables",
    name: "분석소모품 · 이화학장비",
    short: "Consumables",
    desc: "컬럼, 용매, 바이알, 필터, 가스 발생기 등 분석 소모품·주변기기",
    icon: "🧰",
  },
];

const PRODUCTS = [
  // 1. 크로마토그래프 · 질량분석기
  {
    category: "chromatography",
    name: "Nexera Series",
    model: "UHPLC",
    tagline: "초고속 액체 크로마토그래프(UHPLC)",
    desc: "IoT·클라우드 기반 네트워크 기술로 기기 상태를 실시간 모니터링하며, 약 7.8초의 초고속 주입으로 최대 17,000개 샘플을 연속 분석할 수 있는 신개념 UHPLC입니다.",
    specs: ["초저 carryover 0.0003% 이하", "최대 17,000 샘플 연속 분석", "자가 진단/복구 · 이동상 모니터링"],
    featured: true,
  },
  {
    category: "chromatography",
    name: "i-Series",
    model: "HPLC",
    tagline: "올인원 통합형 고속 액체 크로마토그래프(HPLC)",
    desc: "펌프·오토샘플러·컬럼오븐·검출기를 하나의 본체에 통합한 일체형 HPLC로, 터치패널만으로 PC 없이 직접 제어가 가능합니다.",
    specs: ["일체형 콤팩트 설계", "터치패널 직접 제어", "루틴 분석 자동화"],
    featured: false,
  },
  {
    category: "chromatography",
    name: "LCMS-8060 NX",
    model: "LC-MS/MS",
    tagline: "삼중사극자 액체 크로마토그래프 질량분석기",
    desc: "초고감도·고속 스캔을 구현한 삼중사극자 LC/MS로, 의약품·식품안전·임상 연구의 정밀 정량 분석에 최적화되어 있습니다.",
    specs: ["고감도 삼중사극자(QqQ)", "초고속 폴라리티 전환", "의약·식품·임상 정량"],
    featured: true,
  },
  {
    category: "chromatography",
    name: "LCMS-9030",
    model: "Q-TOF",
    tagline: "사극자 비행시간형 LC 질량분석기",
    desc: "사극자-비행시간형(Q-TOF) 결합으로 정확질량과 고분해능 데이터를 제공하여 미지 물질 동정 및 구조 분석에 활용됩니다.",
    specs: ["고분해능 정확질량 측정", "미지물질 동정·구조 분석", "대사체·단백체 연구"],
    featured: false,
  },
  {
    category: "chromatography",
    name: "Nexis GC-2030",
    model: "GC",
    tagline: "가스 크로마토그래프",
    desc: "고감도 검출기와 직관적 터치패널을 탑재한 차세대 가스 크로마토그래프로, 잔류농약·휘발성 유기물 분석에 폭넓게 사용됩니다.",
    specs: ["고감도 캐필러리 GC", "터치패널 직접 제어", "휘발성·반휘발성 분석"],
    featured: false,
  },
  {
    category: "chromatography",
    name: "GCMS-QP2020 NX",
    model: "GC-MS",
    tagline: "단일사극자 가스 크로마토그래프 질량분석기",
    desc: "고감도·고속 스캔의 단일사극자 GC/MS로, 향기 성분·휘발성 유기물·식품 분석 등 폭넓은 정성·정량에 사용됩니다.",
    specs: ["고속 스캔 단일사극자", "향기·VOC·식품 분석", "광범위 라이브러리 검색"],
    featured: false,
  },
  {
    category: "chromatography",
    name: "GCMS-TQ8050 NX",
    model: "GC-MS/MS",
    tagline: "삼중사극자 가스 크로마토그래프 질량분석기",
    desc: "초고감도 삼중사극자 GC/MS로, 식품 잔류농약·환경 오염물질 등 극미량 성분의 정밀 정량에 강점을 가집니다.",
    specs: ["극미량(ppt 수준) 정량", "잔류농약·다이옥신 분석", "고속 MRM 측정"],
    featured: true,
  },

  // 2. 광분석장치
  {
    category: "spectroscopy",
    name: "UV-1900i",
    model: "UV-VIS",
    tagline: "자외·가시광 분광광도계",
    desc: "초고속 스캔과 넓은 측정 파장 범위를 갖춘 자외·가시광 분광광도계로, 정량/정성 분석과 흡광도 측정에 활용됩니다.",
    specs: ["고속 파장 스캔", "넓은 측정 파장 범위", "정량·정성·흡광도 측정"],
    featured: false,
  },
  {
    category: "spectroscopy",
    name: "IRSpirit",
    model: "FTIR",
    tagline: "적외선 분광광도계(FTIR)",
    desc: "콤팩트한 본체로 고성능을 구현한 푸리에 변환 적외선 분광광도계로, 유기물·고분자의 구조 분석과 이물 동정에 사용됩니다.",
    specs: ["콤팩트 고성능 FTIR", "유기물·고분자 구조 분석", "이물·오염물 동정"],
    featured: false,
  },
  {
    category: "spectroscopy",
    name: "RF-6000",
    model: "RF",
    tagline: "형광 분광광도계",
    desc: "세계 최고 수준의 감도를 자랑하는 형광 분광광도계로, 미량 성분 검출과 형광 물질 정량에 뛰어난 성능을 제공합니다.",
    specs: ["최고 수준 검출 감도", "Xe 램프 광원", "미량 형광 성분 정량"],
    featured: false,
  },
  {
    category: "spectroscopy",
    name: "AA-7800",
    model: "AAS",
    tagline: "원자흡광 분광광도계",
    desc: "불꽃/전기가열 방식을 모두 지원하는 원자흡광 분광광도계로, 중금속 등 무기 원소의 정밀 정량 분석에 사용됩니다.",
    specs: ["불꽃/전기가열 겸용", "중금속 정밀 정량", "환경·식품·재료 분석"],
    featured: false,
  },
  {
    category: "spectroscopy",
    name: "ICPE-9800",
    model: "ICP-OES",
    tagline: "ICP 발광 분석 장치",
    desc: "유도결합플라즈마 발광 분석 장치로, 다원소 동시 측정과 넓은 농도 범위 분석을 빠르게 수행합니다.",
    specs: ["다원소 동시 측정", "수직형 토치·축방향 관측", "환경·재료·식품 분석"],
    featured: false,
  },
  {
    category: "spectroscopy",
    name: "ICPMS-2030",
    model: "ICP-MS",
    tagline: "ICP 질량분석기",
    desc: "유도결합플라즈마 질량분석기로, 초미량 다원소 동시 분석을 빠르게 수행하여 환경·반도체·식품 분야에 활용됩니다.",
    specs: ["초미량 다원소 동시 분석", "넓은 농도 동적 범위", "반도체·환경·식품"],
    featured: true,
  },

  // 3. 라이프사이언스 연구장비
  {
    category: "lifescience",
    name: "MultiNA",
    model: "MCE-202",
    tagline: "Microchip 자동 전기영동 장치",
    desc: "마이크로칩 전기영동 방식으로 DNA·RNA를 자동 분리·정량하여, 유전자형 분석과 식품 유전자 검사 등에 사용됩니다.",
    specs: ["DNA/RNA 자동 분리·정량", "유전자형 분석", "식품 유전자 검사"],
    featured: false,
  },
  {
    category: "lifescience",
    name: "MALDI-8020",
    model: "MALDI-TOF",
    tagline: "MALDI-TOF 질량분석기",
    desc: "매트릭스 지원 레이저 탈착 이온화 비행시간형 질량분석기로, 단백질·펩타이드·미생물 동정 등 다양한 연구에 활용됩니다.",
    specs: ["단백질·펩타이드 분석", "미생물 신속 동정", "고분자 화합물 측정"],
    featured: true,
  },
  {
    category: "lifescience",
    name: "QuickGene Series",
    model: "Nucleic Acid",
    tagline: "핵산(DNA·RNA) 추출 장치",
    desc: "독자적인 다공성 멤브레인 기술로 고품질 핵산을 신속·간편하게 추출하는 장치로, 수동형부터 전자동형까지 라인업을 제공합니다.",
    specs: ["고품질 DNA/RNA 추출", "수동·전자동 라인업", "QuickGene Isolation Kit"],
    featured: false,
  },
  {
    category: "lifescience",
    name: "BioSpec-nano",
    model: "Spectro",
    tagline: "라이프사이언스 분광광도계",
    desc: "극미량(μL) 시료로 핵산·단백질 농도를 신속 측정하는 마이크로볼륨 분광광도계입니다.",
    specs: ["μL 단위 미량 측정", "핵산·단백질 정량", "신속 측정 워크플로우"],
    featured: false,
  },
  {
    category: "lifescience",
    name: "PPSQ-53A",
    model: "Sequencer",
    tagline: "단백질/펩타이드 서열 분석기",
    desc: "에드만 분해법 기반의 N-말단 아미노산 서열 분석기로, 단백질의 1차 구조 규명에 사용됩니다.",
    specs: ["N-말단 서열 분석", "단백질 1차 구조 규명", "자동화 분석 플로우"],
    featured: false,
  },
  {
    category: "lifescience",
    name: "LIGHTNIRS",
    model: "fNIRS",
    tagline: "근적외광 뇌기능 이미징 장치",
    desc: "휴대형 근적외광 분광 시스템으로, 비침습적으로 뇌 혈류 변화를 측정하여 뇌기능 연구에 활용됩니다.",
    specs: ["비침습 뇌혈류 측정", "휴대형 fNIRS", "뇌기능 연구"],
    featured: false,
  },

  // 4. 환경측정장치
  {
    category: "environmental",
    name: "TOC-L 시리즈",
    model: "TOC",
    tagline: "총유기탄소분석기",
    desc: "연소 촉매 산화 방식으로 수중 총유기탄소를 고감도·고정밀로 측정하는 분석기로, 수질·제약 세정 검증에 사용됩니다.",
    specs: ["넓은 측정 범위", "연소 촉매 산화 방식", "수질·세정 검증(Cleaning Validation)"],
    featured: true,
  },
  {
    category: "environmental",
    name: "TOC-4200 시리즈",
    model: "On-line TOC",
    tagline: "온라인 총유기탄소분석기",
    desc: "공정/배수 라인에 직접 설치하여 총유기탄소를 24시간 연속 모니터링하는 온라인 분석 시스템으로, 수질 TMS 연동을 지원합니다.",
    specs: ["24시간 연속 모니터링", "수질 TMS 연동", "공정·배수 라인 직결"],
    featured: false,
  },
  {
    category: "environmental",
    name: "7000 시리즈",
    model: "Portable Gas",
    tagline: "휴대용 가스 분석기",
    desc: "현장에서 즉시 가스 성분을 측정할 수 있는 휴대형 분석기(NOA-7000·CGT-7100·SOA-7000)로, 환경 모니터링과 안전 관리에 사용됩니다.",
    specs: ["NOA-7000 / CGT-7100 / SOA-7000", "현장 즉시 측정", "환경·안전 모니터링"],
    featured: false,
  },

  // 5. 재료시험기 · 피로/내구시험
  {
    category: "material",
    name: "AGX-V",
    model: "UTM",
    tagline: "프리미엄 만능 재료 시험기",
    desc: "고속 데이터 샘플링과 고강성 프레임을 갖춘 프리미엄급 만능 재료 시험기로, 정밀한 인장·압축·굽힘 평가를 제공합니다.",
    specs: ["고속 데이터 샘플링", "고강성 프레임", "정밀 물성 평가"],
    featured: false,
  },
  {
    category: "material",
    name: "AGS-X 시리즈",
    model: "UTM",
    tagline: "만능 재료 시험기",
    desc: "인장·압축·굽힘 등 다양한 재료 물성을 정밀 측정하는 만능 재료 시험기로, 금속·플라스틱·고무 등 폭넓은 소재에 대응합니다.",
    specs: ["인장·압축·굽힘 시험", "고정밀 로드셀", "다양한 소재 대응"],
    featured: true,
  },
  {
    category: "material",
    name: "EZ-Test 시리즈",
    model: "Tester",
    tagline: "콤팩트 탁상형 시험기",
    desc: "탁상에 설치 가능한 콤팩트 재료 시험기로, 식품 식감 평가부터 부품 강도 시험까지 간편하게 수행합니다.",
    specs: ["콤팩트 탁상형", "식감·박리·강도 시험", "간편한 조작성"],
    featured: false,
  },
  {
    category: "material",
    name: "SERVOPULSER EHF 시리즈",
    model: "Fatigue",
    tagline: "유압식 피로·내구 시험기",
    desc: "반복 하중을 가하여 재료·부품의 피로 수명과 내구성을 평가하는 유압식 시험기로, 자동차·항공·구조물 분야에 사용됩니다.",
    specs: ["반복 하중 피로 시험", "유압 서보 가진", "자동차·항공·구조물"],
    featured: false,
  },
  {
    category: "material",
    name: "HMV-G 시리즈",
    model: "Hardness",
    tagline: "마이크로 비커스 경도 시험기",
    desc: "비커스·누프 방식으로 재료 표면 경도를 정밀 측정하는 경도 시험기입니다.",
    specs: ["비커스·누프 경도", "마이크로 측정", "자동 압흔 인식"],
    featured: false,
  },

  // 6. 입도분석기 · 전자저울
  {
    category: "particle",
    name: "SALD-7500nano",
    model: "Particle",
    tagline: "나노 입도 분포 측정기",
    desc: "레이저 회절/산란 방식으로 나노미터 영역까지 입자 크기 분포를 측정하는 입도분석기입니다.",
    specs: ["레이저 회절/산란 방식", "나노~마이크로 측정", "입도 분포·형상 분석"],
    featured: true,
  },
  {
    category: "particle",
    name: "AP 시리즈",
    model: "Balance",
    tagline: "분석용 전자 저울",
    desc: "고분해능 정밀 전자저울로, 미량 시료 칭량과 정량 분석 전처리에 사용됩니다.",
    specs: ["고분해능 칭량", "자동 교정 기능", "GLP/GMP 대응"],
    featured: false,
  },
  {
    category: "particle",
    name: "MOC63u",
    model: "Moisture",
    tagline: "가열 건조식 수분 측정기",
    desc: "가열 건조 방식으로 시료의 수분 함량을 신속·정확하게 측정하는 장비입니다.",
    specs: ["가열 건조 방식", "신속 수분 측정", "식품·원료 품질관리"],
    featured: false,
  },
  {
    category: "particle",
    name: "STABLO-AP",
    model: "Ionizer",
    tagline: "정전기 제거 장치",
    desc: "칭량 시 시료에 발생하는 정전기를 제거하여 측정 오차를 줄여주는 제전 장치입니다.",
    specs: ["정전기 제거", "칭량 오차 저감", "전자저울 연동"],
    featured: false,
  },

  // 7. X선 형광분석기
  {
    category: "xray",
    name: "EDX-7200",
    model: "EDX",
    tagline: "에너지 분산형 형광 X선 분석 장치",
    desc: "비파괴로 시료의 원소 조성을 정성·정량 분석하는 에너지 분산형 형광 X선 분석기로, RoHS 규제 대응에 활용됩니다.",
    specs: ["비파괴 원소 분석", "Na~U 광범위 원소", "RoHS 규제 대응"],
    featured: true,
  },
  {
    category: "xray",
    name: "EDX-8100",
    model: "EDX",
    tagline: "고감도 형광 X선 분석 장치",
    desc: "고감도 검출기를 탑재한 에너지 분산형 형광 X선 분석 장치로, 미량 원소까지 정밀하게 분석합니다.",
    specs: ["고감도 미량 원소 분석", "정성·정량 측정", "넓은 원소 범위"],
    featured: false,
  },
  {
    category: "xray",
    name: "Xspecia",
    model: "EDXRF",
    tagline: "형광 X선 분석 솔루션",
    desc: "도금 두께 측정 및 미소부 원소 분석에 특화된 형광 X선 분석 장비입니다.",
    specs: ["도금 두께 측정", "미소부 분석", "고속 매핑"],
    featured: false,
  },

  // 8. 비파괴분석기 · 주사탐침현미경
  {
    category: "ndt",
    name: "InspeXio SMX-225CT FPD HR Plus",
    model: "X-ray CT",
    tagline: "X선 CT 비파괴 검사 장비",
    desc: "X선 투과/CT 촬영으로 제품 내부 결함을 비파괴로 검사하는 장비로, 전자부품·배터리 내부 검사에 사용됩니다.",
    specs: ["내부 결함 비파괴 검사", "고해상도 CT 재구성", "전자부품·배터리 검사"],
    featured: true,
  },
  {
    category: "ndt",
    name: "XSeeker 8000",
    model: "X-ray CT",
    tagline: "콤팩트 X선 CT 검사 장비",
    desc: "콤팩트한 본체로 3D CT 검사를 수행하는 X선 검사 장비로, 부품 내부 구조 관찰과 결함 분석에 사용됩니다.",
    specs: ["3D CT 검사", "콤팩트 설계", "내부 구조 관찰"],
    featured: false,
  },
  {
    category: "ndt",
    name: "MIV-X",
    model: "SAT",
    tagline: "초음파 광 탐상기",
    desc: "초음파를 이용해 재료 내부의 박리·공극 등 결함을 비파괴로 검출하는 탐상 장비입니다.",
    specs: ["초음파 결함 검출", "박리·공극 영상화", "반도체 패키지 검사"],
    featured: false,
  },
  {
    category: "ndt",
    name: "SPM-Nanoa",
    model: "SPM/AFM",
    tagline: "주사탐침현미경 / 원자간력현미경",
    desc: "나노미터 분해능으로 표면 형상과 물성을 측정하는 주사탐침현미경(SPM/AFM)입니다.",
    specs: ["나노 분해능 표면 측정", "형상·물성 매핑", "재료·반도체 연구"],
    featured: false,
  },

  // 9. 분석소모품 · 이화학장비
  {
    category: "consumables",
    name: "HPLC/GC/GPC 컬럼",
    model: "Columns",
    tagline: "분석용 컬럼 라인업",
    desc: "다양한 분리 모드를 지원하는 HPLC·GC·GPC 컬럼으로, 분석 목적에 맞는 최적의 분리 성능을 제공합니다.",
    specs: ["다양한 분리 모드", "재현성 높은 품질", "용도별 최적 선택"],
    featured: false,
  },
  {
    category: "consumables",
    name: "고순도 질소/수소 발생기",
    model: "Gas Gen.",
    tagline: "분석용 가스 발생 장치",
    desc: "분석에 필요한 고순도 질소·수소를 자체 생성하여 가스 봄베 교체 부담을 줄여주는 가스 발생기(ATN-1050·Lab Tower 등)입니다.",
    specs: ["고순도 가스 자체 생성", "봄베 교체 불필요", "안전한 가스 공급"],
    featured: true,
  },
  {
    category: "consumables",
    name: "바이알 · 필터 · 소모품",
    model: "Supplies",
    tagline: "분석 소모품 종합",
    desc: "바이알/캡/인서트, 시린지 필터, 시린지, 가스필터 등 일상 분석에 필요한 소모품을 종합적으로 공급합니다.",
    specs: ["바이알/캡/인서트", "시린지 필터", "가스필터·정화장치"],
    featured: false,
  },
  {
    category: "consumables",
    name: "시약장 · 폐액 수집함",
    model: "Lab Safety",
    tagline: "실험실 안전·보관 제품",
    desc: "냉동형 필터시약장(SP-SSK-SF1/SFD1)과 폐액 안전 보관함, 가스 정화장치(SP-LAC·SP-SSK-GP2) 등 실험실 안전 제품을 제공합니다.",
    specs: ["냉동형 필터시약장", "폐액 안전 보관함", "가스 정화장치"],
    featured: false,
  },
];

// 다른 스크립트에서 사용할 수 있도록 전역으로 노출
window.NETBIX_DATA = { CATEGORIES, PRODUCTS };
